// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 17
// Source File: ArabicShaping.txt
// Unicode Source: https://unicode.org/Public/17.0.0/ucd/ArabicShaping.txt
// Model: gpt-4o-mini
// Generated At: 2026-04-06T15:34:53.973Z
// Fields: 4
export interface ArabicShaping {
  /**
   * Field 0: the code point of a character, in hexadecimal form.
   */
  code_point: string;
  /**
   * Field 1: gives a short schematic name for that character.
   */
  name: string;
  /**
   * Field 2: defines the joining type (property name: Joining_Type).
   */
  joining_type: "R" | "L" | "D" | "C" | "U" | "T";
  /**
   * Field 3: defines the joining group (property name: Joining_Group).
   */
  joining_group: string;
}

export const ARABIC_SHAPING_FIELDS = ["code_point", "name", "joining_type", "joining_group"];
