// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 13

//#region data-files/v13.0.0/ArabicShaping.txt
/**
 * This interface defines the properties for Arabic shaping, including the code point, schematic name, joining type, and joining group.
 */
export interface ArabicShaping {
    /**
     * The code point of a character in 4-digit hexadecimal form.
     * Example: '0629'
     */
    code_point: string;

    /**
     * A short schematic name for the character, descriptive of its shape.
     * Example: 'TEH MARBUTA'
     */
    schematic_name: string;

    /**
     * The joining type of the character, which can be one of the following:
     * - "R" for Right_Joining
     * - "L" for Left_Joining
     * - "D" for Dual_Joining
     * - "C" for Join_Causing
     * - "U" for Non_Joining
     * - "T" for Transparent
     * Example: 'R'
     */
    joining_type: "R" | "L" | "D" | "C" | "U" | "T";

    /**
     * The joining group of the character, based on its schematic name.
     * Example: 'TEH_MARBUTA'
     */
    joining_group: string;
}

export const ARABIC_SHAPING_FIELDS = [
    "code_point",
    "schematic_name",
    "joining_type",
    "joining_group"
];
//#endregion

//#region data-files/v13.0.0/BidiBrackets.txt
/**
 * BidiBrackets interface represents the mapping of Unicode characters that are treated as bracket pairs by the Unicode Bidirectional Algorithm.
 */
export interface BidiBrackets {
    /**
     * Unicode code point value, represented as a hexadecimal value.
     * Example: "U+298D"
     */
    unicode_code_point: string;

    /**
     * Bidi_Paired_Bracket property value, a code point value or <none>.
     * Example: "U+298E" or "<none>"
     */
    bidi_paired_bracket: string;

    /**
     * Bidi_Paired_Bracket_Type property value, one of the following:
     *   - "o" for Open
     *   - "c" for Close
     *   - "n" for None
     * Example: "o"
     */
    bidi_paired_bracket_type: "o" | "c" | "n";
}

export const BIDI_BRACKETS_FIELDS = [
    "unicode_code_point",
    "bidi_paired_bracket",
    "bidi_paired_bracket_type"
];
//#endregion

//#region data-files/v13.0.0/BidiCharacterTest.txt
/**
 * BidiCharacterTest interface represents a conformance test for implementations of the Unicode Bidirectional Algorithm.
 */
export interface BidiCharacterTest {
    /**
     * A sequence of hexadecimal code point values separated by space.
     * Example: "0041 0052 0061"
     */
    code_points: string;

    /**
     * A value representing the paragraph direction:
     * - 0 represents left-to-right
     * - 1 represents right-to-left
     * - 2 represents auto-LTR according to rules P2 and P3 of the algorithm.
     * Example: 0
     */
    paragraph_direction: "0" | "1" | "2";

    /**
     * The resolved paragraph embedding level.
     * Example: 0
     */
    resolved_paragraph_embedding_level: number;

    /**
     * A list of resolved levels; characters removed in rule X9 are indicated with an 'x'.
     * Example: "0 1 x 2"
     */
    resolved_levels: string;

    /**
     * A list of indices showing the resulting visual ordering from left to right; characters with a resolved level of 'x' are skipped.
     * Example: "0 1 3"
     */
    visual_ordering_indices: string;
}

export const BIDI_CHARACTER_TEST_FIELDS = [
    "code_points",
    "paragraph_direction",
    "resolved_paragraph_embedding_level",
    "resolved_levels",
    "visual_ordering_indices"
];
//#endregion

//#region data-files/v13.0.0/BidiMirroring.txt
/**
 * BidiMirroring interface represents the mapping of Unicode characters that have the Bidi_Mirrored=Yes property value.
 * Each mapping consists of a source code point and its corresponding mirrored code point.
 */
export interface BidiMirroring {
    /**
     * The source code point represented as a hexadecimal value (4 to 6 digits).
     * Example: '0041' for 'A'.
     */
    source: string;

    /**
     * The mirrored code point represented as a hexadecimal value (4 to 6 digits).
     * Example: '0061' for 'a'.
     */
    mirrored: string;
}

export const BIDI_MIRRORING_FIELDS = [
    "source",
    "mirrored"
];
//#endregion

//#region data-files/v13.0.0/BidiTest.txt
/**
 * This interface defines the structure for the BidiTest conformance test data.
 * It includes properties for levels, reordering, and input data for testing the Unicode Bidi Algorithm.
 */
export interface BidiTest {
  /**
   * An ordered space-delimited list of numbers indicating the resulting levels
   * for each input property value. The UBA does not assign levels to certain values;
   * those are indicated with an x. Example: "1 0" or "x 1 x 2".
   */
  levels: string;

  /**
   * An ordered space-delimited list of numbers indicating the resulting
   * visual ordering from left to right. The numbers are zero-based, and
   * are indexes into the input string. Items with a level of x are skipped.
   * Example: "1 0" or "3 1".
   */
  reorder: string;

  /**
   * An ordered list of BIDI property values followed by a hex bitset for
   * paragraph levels (P): 1 = auto-LTR, 2 = LTR, 4 = RTL. Example: "L LRE R R; 7".
   */
  data: string;
}

export const BIDI_TEST_FIELDS = [
  "levels",
  "reorder",
  "data"
];
//#endregion

//#region data-files/v13.0.0/Blocks.txt
/**
 * Interface representing the Unicode Character Database blocks.
 */
export interface Blocks {
    /**
     * The starting code point of the block.
     * Format: U+XXXX (e.g., U+0041)
     */
    start_code: string;

    /**
     * The ending code point of the block.
     * Format: U+XXXX (e.g., U+007A)
     */
    end_code: string;

    /**
     * The name of the block.
     * Example: "Basic Latin"
     */
    block_name: string;
}

export const BLOCKS_FIELDS = [
    "start_code",
    "end_code",
    "block_name"
];
//#endregion

//#region data-files/v13.0.0/CJKRadicals.txt
/**
 * Interface representing the mapping from CJK radical numbers to characters.
 */
export interface CJKRadicals {
    /**
     * The CJK radical number, which matches the regular expression [1-9][0-9]{0,2}'?.
     * Example: "1", "2'"
     */
    cjk_radical_number: string;

    /**
     * The CJK radical character corresponding to the radical number.
     * Example: "氵"
     */
    cjk_radical_character: string;

    /**
     * The CJK unified ideograph formed from the radical only.
     * Example: "水"
     */
    cjk_unified_ideograph: string;
}

export const CJK_RADICALS_FIELDS = [
    "cjk_radical_number",
    "cjk_radical_character",
    "cjk_unified_ideograph"
];
//#endregion

//#region data-files/v13.0.0/CaseFolding.txt
/**
 * Interface representing the case folding properties as defined in the Unicode Character Database.
 */
export interface CaseFolding {
    /**
     * The Unicode code point of the character.
     * Format: Hexadecimal (e.g., 0041 for 'A')
     */
    code: string;

    /**
     * The status of the case folding mapping.
     * Possible values: "C" (common), "F" (full), "S" (simple), "T" (Turkic special case)
     */
    status: "C" | "F" | "S" | "T";

    /**
     * The mapping for the case folding.
     * Format: A string of characters, separated by spaces for full mappings.
     */
    mapping: string;

    /**
     * The name of the character.
     * This is a descriptive name for the character represented by the code point.
     */
    name: string;
}

export const CASE_FOLDING_FIELDS = [
    "code",
    "status",
    "mapping",
    "name"
];
//#endregion

//#region data-files/v13.0.0/CompositionExclusions.txt
/**
 * This interface represents the Composition Exclusions defined in UAX #15, Unicode Normalization Forms.
 */
export interface CompositionExclusions {
    /**
     * The date when the data was last updated.
     * Format: YYYY-MM-DD, HH:MM:SS GMT
     * Example: "2019-10-15, 18:27:00 GMT"
     */
    date: string;

    /**
     * The copyright information for the data.
     * Example: "© 2019 Unicode®, Inc."
     */
    copyright: string;

    /**
     * The URL for the terms of use.
     * Example: "http://www.unicode.org/terms_of_use.html"
     */
    terms_of_use_url: string;

    /**
     * The URL for the Unicode Character Database documentation.
     * Example: "http://www.unicode.org/reports/tr44/"
     */
    unicode_character_database_documentation_url: string;

    /**
     * A description of the file's content and purpose.
     */
    description: string;

    /**
     * The URL for more information on the composition exclusions.
     * Example: "http://www.unicode.org/unicode/reports/tr15/#Primary_Exclusion_List_Table"
     */
    composition_exclusions_info_url: string;

    /**
     * The URL for the derived property Full_Composition_Exclusion.
     * Example: "DerivedNormalizationProps.txt"
     */
    full_composition_exclusion_url: string;
}

export const COMPOSITION_EXCLUSIONS_FIELDS = [
    "date",
    "copyright",
    "terms_of_use_url",
    "unicode_character_database_documentation_url",
    "description",
    "composition_exclusions_info_url",
    "full_composition_exclusion_url"
];
//#endregion

//#region data-files/v13.0.0/DerivedAge.txt
/**
 * This interface represents the derived property data from the Unicode Character Database.
 */
export interface DerivedAge {
    /**
     * The date when the code point was assigned in Unicode.
     * Format: YYYY-MM-DD, HH:MM:SS GMT
     * Example: "2019-09-08, 23:30:59 GMT"
     */
    assigned_date: string;
    
    /**
     * The version of Unicode when the code point was assigned.
     * Format: Major.Minor.Patch
     * Example: "1.1.0"
     */
    unicode_version: string;
    
    /**
     * Indicates the type of code point assigned.
     * Possible values: "graphic", "format", "control", "private-use", "surrogate", "noncharacter"
     */
    code_point_type: "graphic" | "format" | "control" | "private-use" | "surrogate" | "noncharacter";
}

export const DERIVED_AGE_FIELDS = [
    "assigned_date",
    "unicode_version",
    "code_point_type"
];
//#endregion

//#region data-files/v13.0.0/DerivedCoreProperties.txt
/**
 * Interface representing the properties of the Unicode Character Database.
 */
export interface DerivedCoreProperties {
    /**
     * The Unicode character code point in hexadecimal format.
     * Example: "U+0041" for the character 'A'.
     */
    code_point: string;

    /**
     * The general category of the character.
     * Example: "Lu" for uppercase letters.
     */
    general_category: string;

    /**
     * The canonical combining class of the character.
     * Example: "0" for base characters.
     */
    canonical_combining_class: string;

    /**
     * The bidirectional category of the character.
     * Example: "L" for left-to-right.
     */
    bidirectional_category: string;

    /**
     * The decomposition mapping of the character.
     * Example: "0041" for 'A' decomposed to its base form.
     */
    decomposition_mapping: string;

    /**
     * The numeric value of the character, if applicable.
     * Example: "1.0" for the character '1'.
     */
    numeric_value: string;

    /**
     * The script associated with the character.
     * Example: "Latn" for Latin script.
     */
    script: string;

    /**
     * The uppercase mapping of the character.
     * Example: "A" for lowercase 'a'.
     */
    uppercase_mapping: string;

    /**
     * The lowercase mapping of the character.
     * Example: "a" for uppercase 'A'.
     */
    lowercase_mapping: string;

    /**
     * The titlecase mapping of the character.
     * Example: "A" for titlecase 'a'.
     */
    titlecase_mapping: string;
}

export const DERIVED_CORE_PROPERTIES_FIELDS = [
    "code_point",
    "general_category",
    "canonical_combining_class",
    "bidirectional_category",
    "decomposition_mapping",
    "numeric_value",
    "script",
    "uppercase_mapping",
    "lowercase_mapping",
    "titlecase_mapping"
];
//#endregion

//#region data-files/v13.0.0/DerivedNormalizationProps.txt
/**
 * Interface representing the properties of DerivedNormalizationProps.
 */
export interface DerivedNormalizationProps {
    /**
     * The normalization form, which can be one of the following: "NFC", "NFD", "NFKC", "NFKD".
     * Example: "NFC"
     */
    normalization_form: "NFC" | "NFD" | "NFKC" | "NFKD";

    /**
     * A boolean indicating whether to use compatibility normalization.
     * Example: true
     */
    compatibility: boolean;

    /**
     * The version of the normalization algorithm used.
     * Example: "13.0.0"
     */
    version: string;

    /**
     * An optional description of the normalization process.
     * Example: "Normalization process for Unicode characters."
     */
    description?: string;
}

export const DERIVED_NORMALIZATION_PROPS_FIELDS = [
    "normalization_form",
    "compatibility",
    "version",
    "description"
];
//#endregion

//#region data-files/v13.0.0/EastAsianWidth.txt
/**
 * EastAsianWidth
 *
 * This interface represents the East Asian Width property of Unicode characters.
 *
 * The East Asian Width property can take one of the following values:
 * - "A": Ambiguous
 * - "F": Full-width
 * - "H": Half-width
 * - "N": Neutral
 * - "Na": Narrow
 * - "W": Wide
 *
 * All code points, assigned or unassigned, that are not listed explicitly are given the value "N".
 * The unassigned code points in specific blocks default to "W". For example:
 * - CJK Unified Ideographs Extension A: U+3400..U+4DBF
 * - CJK Unified Ideographs: U+4E00..U+9FFF
 * - CJK Compatibility Ideographs: U+F900..U+FAFF
 *
 * Character ranges are specified as for other property files in the Unicode Character Database.
 *
 * For more information, see UAX #11: East Asian Width at http://www.unicode.org/reports/tr11/
 */
export interface EastAsianWidth {
    code_point: string;
    east_asian_width: "A" | "F" | "H" | "N" | "Na" | "W";
}

export const EAST_ASIAN_WIDTH_FIELDS = [
    "code_point",
    "east_asian_width"
];
//#endregion

//#region data-files/v13.0.0/EmojiSources.txt
/**
 * Interface representing the mappings between Unicode code points and Shift-JIS codes for cell phone carrier symbols.
 *
 * Each mapping is symmetric for equivalent Unicode and carrier symbols or sequences.
 * This interface includes the following fields:
 *
 * - `unicode_code_point_or_sequence`: The Unicode code point or sequence (e.g., "U+1F600").
 * - `docomo_shift_jis_code`: The DoCoMo Shift-JIS code (e.g., "0xF8A0").
 * - `kddi_shift_jis_code`: The KDDI Shift-JIS code (e.g., "0xF8A1").
 * - `softbank_shift_jis_code`: The SoftBank Shift-JIS code (e.g., "0xF8A2").
 */
export interface EmojiSources {
  unicode_code_point_or_sequence: string;
  docomo_shift_jis_code?: string;
  kddi_shift_jis_code?: string;
  softbank_shift_jis_code?: string;
}

export const EMOJI_SOURCES_FIELDS = [
  "unicode_code_point_or_sequence",
  "docomo_shift_jis_code",
  "kddi_shift_jis_code",
  "softbank_shift_jis_code"
];
//#endregion

//#region data-files/v13.0.0/EquivalentUnifiedIdeograph.txt
/**
 * This interface defines the mappings from code points or code point ranges to equivalent CJK unified ideographs.
 * Each mapping consists of a source code point or range and its corresponding unified ideograph.
 */
export interface EquivalentUnifiedIdeograph {
    /**
     * A code point or code point range represented as a variable-length hexadecimal value with 4 to 6 digits.
     * Example: "4E00" or "4E00-4E0F"
     */
    source: string;

    /**
     * A code point represented as a variable-length hexadecimal value with 4 to 6 digits.
     * Example: "4E8C"
     */
    target: string;
}

export const EQUIVALENT_UNIFIED_IDEOGRAPH_FIELDS = [
    "source",
    "target"
];
//#endregion

//#region data-files/v13.0.0/HangulSyllableType.txt
/**
 * Interface representing the Hangul Syllable Type data.
 */
export interface HangulSyllableType {
    /**
     * The Hangul syllable type code.
     * Format: "A", "B", etc.
     */
    code: string;
    /**
     * The description of the syllable type.
     * Example: "Consonant + Vowel"
     */
    description: string;
    /**
     * The number of characters in the syllable type.
     * Format: integer
     */
    character_count: number;
}

export const HANGUL_SYLLABLE_TYPE_FIELDS = [
    "code",
    "description",
    "character_count"
];
//#endregion

//#region data-files/v13.0.0/IndicPositionalCategory.txt
/**
 * This interface defines the Indic_Positional_Category property aimed at specifying syllabic structure for Indic scripts.
 * It includes properties for Unicode code points and their corresponding positional categories.
 */
export interface IndicPositionalCategory {
    /**
     * Unicode code point value or range of code point values.
     * Example: "U+0BC1" or "U+0BC1..U+0BC2"
     */
    unicode_code_point: string;

    /**
     * Indic_Positional_Category property value.
     * Possible values include "Top", "Bottom", "Left", "Right", etc.
     * Example: "Top"
     */
    indic_positional_category: "Top" | "Bottom" | "Left" | "Right";

    /**
     * Comment field showing the General_Category property value, Unicode character name(s), and code point count.
     * Example: "# Lo; TAMIL VOWEL SIGN U; [2]"
     */
    comment: string;
}

export const INDIC_POSITIONAL_CATEGORY_FIELDS = [
    "unicode_code_point",
    "indic_positional_category",
    "comment"
];
//#endregion

//#region data-files/v13.0.0/IndicSyllabicCategory.txt
/**
 * This interface defines the Indic Syllabic Category property, which is aimed at analyzing and processing Indic scripts.
 *
 * The property specifies the syllabic structure and segmentation rules for Indic scripts.
 *
 * The following scripts are assessed as Indic in the structural sense:
 * Ahom, Balinese, Batak, Bengali, Bhaiksuki, Brahmi, Buginese, Buhid,
 * Chakma, Cham, Devanagari, Dives Akuru, Dogra, Grantha, Gujarati,
 * Gunjala Gondi, Gurmukhi, Hanunoo, Javanese, Kaithi, Kannada,
 * Kayah Li, Kharoshthi, Khmer, Khojki, Khudawadi, Lao, Lepcha, Limbu,
 * Mahajani, Makasar, Malayalam, Marchen, Masaram Gondi, Meetei Mayek,
 * Modi, Multani, Myanmar, Nandinagari, Newa, New Tai Lue, Oriya,
 * Phags-pa, Rejang, Saurashtra, Sharada, Siddham, Sinhala, Soyombo,
 * Sundanese, Syloti Nagri, Tagalog, Tagbanwa, Tai Le, Tai Tham,
 * Tai Viet, Takri, Tamil, Telugu, Thai, Tibetan, Tirhuta, and
 * Zanabazar Square.
 *
 * All characters for all other scripts not in that list take the default value for this property.
 */
export interface IndicSyllabicCategory {
    /**
     * Unicode code point value or range of code point values.
     * Example: "U+0900" or "U+0900-U+0903"
     */
    unicode_code_point: string;
    /**
     * Indic Syllabic Category property value.
     * Example: "Vowel", "Consonant"
     */
    indic_syllabic_category: "Vowel" | "Consonant" | "Dependent Vowel" | "Consonant With Vowel" | "Consonant With Vowel Modifier" | "Nukta" | "Virama" | "Other";
}

export const INDIC_SYLLABIC_CATEGORY_FIELDS = [
    "unicode_code_point",
    "indic_syllabic_category"
];
//#endregion

//#region data-files/v13.0.0/Jamo.txt
/**
 * Interface representing the Jamo_Short_Name property.
 */
export interface Jamo {
    /**
     * The code point of a conjoining jamo character in 4-digit hexadecimal form.
     * Example: '1100'
     */
    code_point: string;

    /**
     * The Jamo_Short_Name as a one-, two-, or three-character ASCII string.
     * Example: 'ᄀ', 'ᄁ', 'ᄂ'
     */
    jamo_short_name: string;
}

export const JAMO_FIELDS = [
    "code_point",
    "jamo_short_name"
];
//#endregion

//#region data-files/v13.0.0/LineBreak.txt
/**
 * Line_Break Property
 *
 * This interface represents the line break properties of Unicode characters.
 * Each entry consists of a Unicode code point value or range and its corresponding line break property.
 */
export interface LineBreak {
    /**
     * Unicode code point value or range of code point values.
     * Example: U+0041 for 'A' or U+0041..U+0042 for the range 'A' to 'B'.
     */
    code_point: string;

    /**
     * Line_Break property, which can be one of the following:
     * - Non-tailorable: "BK", "CM", "CR", "GL", "LF", "NL", "SP", "WJ", "ZW", "ZWJ"
     * - Tailorable: "AI", "AL", "B2", "BA", "BB", "CB", "CJ", "CL", "CP", "EB",
     *   "EM", "EX", "H2", "H3", "HL", "HY", "ID", "IN", "IS", "JL",
     *   "JT", "JV", "NS", "NU", "OP", "PO", "PR", "QU", "RI", "SA",
     *   "SG", "SY", "XX"
     *
     * All code points not explicitly listed are given the value "XX".
     * Unassigned code points in specific blocks default to "ID" or "PR" as specified.
     */
    line_break_property: "BK" | "CM" | "CR" | "GL" | "LF" | "NL" | "SP" | "WJ" | "ZW" | "ZWJ" | 
    "AI" | "AL" | "B2" | "BA" | "BB" | "CB" | "CJ" | "CL" | "CP" | "EB" | 
    "EM" | "EX" | "H2" | "H3" | "HL" | "HY" | "ID" | "IN" | "IS" | "JL" | 
    "JT" | "JV" | "NS" | "NU" | "OP" | "PO" | "PR" | "QU" | "RI" | "SA" | 
    "SG" | "SY" | "XX";
}

export const LINE_BREAK_FIELDS = ["code_point", "line_break_property"];
//#endregion

//#region data-files/v13.0.0/NameAliases.txt
/**
 * This interface defines the formal name aliases for Unicode characters.
 */
export interface NameAliases {
  /**
   * The code point of the Unicode character, represented as a hexadecimal string.
   * Example: "U+0041" for the character 'A'.
   */
  code_point: string;

  /**
   * The alias for the Unicode character, which can be a formal name or an abbreviation.
   * Example: "LATIN CAPITAL LETTER A" or "C1".
   */
  alias: string;

  /**
   * The type of the alias, which can be one of the following: "correction", "control", "alternate", "figment", "abbreviation".
   * Comparisons of type labels should ignore case.
   */
  type: "correction" | "control" | "alternate" | "figment" | "abbreviation";
}

export const NAME_ALIASES_FIELDS = [
  "code_point",
  "alias",
  "type"
];
//#endregion

//#region data-files/v13.0.0/NamedSequences.txt
/**
 * This interface represents the Unicode Named Character Sequences.
 */
export interface NamedSequences {
  /**
   * The name of the sequence.
   * Example: "EXAMPLE NAME"
   */
  name: string;
  /**
   * The code point sequence for USI, represented as a string of space-separated code points.
   * Example: "1000 1001 1002"
   */
  code_point_sequence: string;
}

export const NAMED_SEQUENCES_FIELDS = [
  "name",
  "code_point_sequence"
];
//#endregion

//#region data-files/v13.0.0/NamedSequencesProv.txt
/**
 * Provisional Unicode Named Character Sequences
 *
 * This interface represents the provisional named character sequences as defined in the Unicode Character Database.
 */
export interface NamedSequencesProv {
    /**
     * The name of the sequence.
     * Example: "EXAMPLE NAME"
     */
    name: string;

    /**
     * The code point sequence for USI, represented as a string of space-separated code points.
     * Example: "1000 1001 1002"
     */
    code_point_sequence: string;
}

export const NAMED_SEQUENCES_PROV_FIELDS = [
    "name",
    "code_point_sequence"
];
//#endregion

//#region data-files/v13.0.0/NormalizationCorrections.txt
/**
 * Interface representing normalization corrections in Unicode.
 */
export interface NormalizationCorrections {
    /**
     * Unicode code point, represented as a hexadecimal string (e.g., "U+0041").
     */
    unicode_code_point: string;

    /**
     * Original (erroneous) decomposition of the character.
     */
    original_decomposition: string;

    /**
     * Corrected decomposition of the character.
     */
    corrected_decomposition: string;

    /**
     * Version of Unicode for which the correction was entered, in n.n.n format (e.g., "12.0.0").
     */
    unicode_version: string;

    /**
     * Comment indicating the Unicode Corrigendum which documents the correction.
     */
    comment: string;
}

export const NORMALIZATION_CORRECTIONS_FIELDS = [
    "unicode_code_point",
    "original_decomposition",
    "corrected_decomposition",
    "unicode_version",
    "comment"
];
//#endregion

//#region data-files/v13.0.0/NormalizationTest.txt
/**
 * Interface representing the normalization test suite data.
 */
export interface NormalizationTest {
    /**
     * The source code points to be normalized.
     * Example: "U+0041; U+0061"
     */
    source: string;

    /**
     * The normalized form in NFC.
     * Example: "U+0041"
     */
    nfc: string;

    /**
     * The normalized form in NFD.
     * Example: "U+0061"
     */
    nfd: string;

    /**
     * The normalized form in NFKC.
     * Example: "U+0041"
     */
    nfkc: string;

    /**
     * The normalized form in NFKD.
     * Example: "U+0061"
     */
    nfkd: string;
}

export const NORMALIZATION_TEST_FIELDS = [
    "source",
    "nfc",
    "nfd",
    "nfkc",
    "nfkd"
];
//#endregion

//#region data-files/v13.0.0/NushuSources.txt
/**
 * Interface representing the Unicode Character Database for Nushu sources.
 */
export interface NushuSources {
    /**
     * The date of the data file in GMT format.
     * Example: "2019-09-09T19:52:00Z"
     */
    date: string;

    /**
     * The copyright information for the data.
     * Example: "© 2019 Unicode®, Inc."
     */
    copyright: string;

    /**
     * The URL for the terms of use.
     * Example: "http://www.unicode.org/terms_of_use.html"
     */
    terms_of_use: string;

    /**
     * The URL for the documentation of the Unicode Character Database.
     * Example: "http://www.unicode.org/reports/tr44/"
     */
    documentation_url: string;
}

export const NUSHU_SOURCES_FIELDS = [
    "date",
    "copyright",
    "terms_of_use",
    "documentation_url"
];
//#endregion

//#region data-files/v13.0.0/PropList.txt
/**
 * Interface representing the Unicode Character Database properties.
 */
export interface PropList {
    /**
     * The date when the data was generated in GMT format.
     * Example: "2019-11-27T03:13:28Z"
     */
    date: string;
    /**
     * The copyright information for the Unicode data.
     * Example: "© 2019 Unicode®, Inc."
     */
    copyright: string;
    /**
     * The URL for the terms of use for the Unicode data.
     * Example: "http://www.unicode.org/terms_of_use.html"
     */
    terms_of_use: string;
    /**
     * The URL for the documentation of the Unicode Character Database.
     * Example: "http://www.unicode.org/reports/tr44/"
     */
    documentation_url: string;
}

export const PROP_LIST_FIELDS = [
    "date",
    "copyright",
    "terms_of_use",
    "documentation_url"
];
//#endregion

//#region data-files/v13.0.0/PropertyAliases.txt
/**
 * This interface contains aliases for properties used in the Unicode Character Database (UCD).
 * The names can be used for XML formats of UCD data, for regular-expression property tests,
 * and other programmatic textual descriptions of Unicode data.
 *
 * Each property has a short name and a long name, with additional aliases possible.
 *
 * Note: Property value names are not unique across properties, and some property names may
 * be the same as property value names. The combination of property value and property name
 * is unique.
 */
export interface PropertyAliases {
    /**
     * Short name for the property, typically an abbreviation or a duplicate of the long name.
     * Example: "AL"
     */
    short_name: string;

    /**
     * Long name for the property, typically the formal name used in documentation.
     * Example: "Arabic Letter"
     */
    long_name: string;

    /**
     * Additional aliases for the property, if any.
     * Example: "Arabic Letter, AL"
     */
    additional_aliases?: string[];
}

export const PROPERTY_ALIASES_FIELDS = [
    "short_name",
    "long_name",
    "additional_aliases"
];
//#endregion

//#region data-files/v13.0.0/PropertyValueAliases.txt
/**
 * This interface represents the aliases for property values used in the Unicode Character Database (UCD).
 *
 * Each property value name consists of the following fields:
 * - property: The property for which the property value name is used.
 * - short_name: The short name for the property value, typically an abbreviation or duplicate of the long name.
 * - long_name: The long name for the property value, typically the formal name used in documentation.
 *
 * In the case of Canonical_Combining_Class (ccc), there are 4 fields:
 * - property: The property for which the property value name is used.
 * - numeric: A numeric representation of the property value.
 * - short_name: The short name for the property value.
 * - long_name: The long name for the property value.
 *
 * Note: Property value names are not unique across properties, and some property names may be the same as property value names.
 */
export interface PropertyValueAliases {
  property: string;
  short_name: string;
  long_name: string;
  numeric?: number;
}

export const PROPERTY_VALUE_ALIASES_FIELDS = [
  "property",
  "short_name",
  "long_name",
  "numeric"
];
//#endregion

//#region data-files/v13.0.0/ScriptExtensions.txt
/**
 * The ScriptExtensions interface represents the Unicode Script Extensions property,
 * indicating which characters are commonly used with more than one script.
 * Each code point has one or more property values, which are Script property values.
 */
export interface ScriptExtensions {
    /**
     * A set of one or more abbreviated Script property values.
     * The ordering of the values in that set is not material, but for stability in presentation,
     * it is given here as alphabetical.
     * 
     * Example: "Latin", "Cyrillic"
     */
    script_extensions: Array<"Latin" | "Cyrillic" | "Arabic" | "Greek" | "Hebrew" | "Devanagari" | "Thai" | "Bengali" | "Gurmukhi" | "Gujarati" | "Oriya" | "Tamil" | "Telugu" | "Kannada" | "Malayalam" | "Sinhala" | "Tibetan" | "Myanmar" | "Khmer" | "Lao" | "Vietnamese" | "Hiragana" | "Katakana" | "Han" | "Hangul" | "Bopomofo" | "Yi" | "Cherokee" | "Ethiopic" | "Syriac" | "ArabicSupplement" | "CyrillicSupplement" | "LatinSupplement">;

    /**
     * The list of code points associated with the script extensions value,
     * listed in code point order.
     * 
     * Example: 0x0041, 0x0042, 0x0043
     */
    code_points: Array<number>;
}

export const SCRIPT_EXTENSIONS_FIELDS = ["script_extensions", "code_points"];
//#endregion

//#region data-files/v13.0.0/Scripts.txt
/**
 * Interface representing the Unicode Character Database Scripts.
 */
export interface Scripts {
    /**
     * The date when the data was generated, in ISO 8601 format.
     * Example: "2020-01-22T00:07:43Z"
     */
    date: string;
    /**
     * Copyright information regarding the Unicode data.
     * Example: "© 2020 Unicode®, Inc."
     */
    copyright: string;
    /**
     * A URL to the terms of use for the Unicode data.
     * Example: "http://www.unicode.org/terms_of_use.html"
     */
    terms_of_use_url: string;
    /**
     * A URL to the Unicode Character Database documentation.
     * Example: "http://www.unicode.org/reports/tr44/"
     */
    documentation_url: string;
    /**
     * A URL to the Unicode Script Property report.
     * Example: "http://www.unicode.org/reports/tr24/"
     */
    script_property_url: string;
    /**
     * A URL to the specific sections of the Unicode Script Property report.
     * Example: "http://www.unicode.org/reports/tr24/#Assignment_Script_Values"
     */
    assignment_script_values_url: string;
    /**
     * A URL to the sections regarding Assignment ScriptX Values.
     * Example: "http://www.unicode.org/reports/tr24/#Assignment_ScriptX_Values"
     */
    assignment_scriptx_values_url: string;
}

export const SCRIPTS_FIELDS = [
    "date",
    "copyright",
    "terms_of_use_url",
    "documentation_url",
    "script_property_url",
    "assignment_script_values_url",
    "assignment_scriptx_values_url"
];
//#endregion

//#region data-files/v13.0.0/SpecialCasing.txt
/**
 * This interface represents the special casing mappings for Unicode characters.
 */
export interface SpecialCasing {
    /**
     * The Unicode code point of the character, expressed in hexadecimal format.
     * Example: "0041" for 'A'
     */
    code: string;

    /**
     * The lowercase mapping of the character, expressed as character values in hex.
     * If there are multiple characters, they are separated by spaces.
     * Example: "0061" for 'a'
     */
    lower: string;

    /**
     * The titlecase mapping of the character, expressed as character values in hex.
     * Example: "0041" for 'A'
     */
    title: string;

    /**
     * The uppercase mapping of the character, expressed as character values in hex.
     * Example: "0041" for 'A'
     */
    upper: string;

    /**
     * An optional list of conditions that override the normal behavior of casing.
     * This can include language IDs or casing contexts, separated by spaces.
     * Example: "en US" or "Not_en"
     */
    condition_list?: string;

    /**
     * A comment providing additional information about the mapping.
     * Example: "Common casing for Latin characters"
     */
    comment?: string;
}

export const SPECIAL_CASING_FIELDS = [
    "code",
    "lower",
    "title",
    "upper",
    "condition_list",
    "comment"
];
//#endregion

//#region data-files/v13.0.0/StandardizedVariants.txt
/**
 * Interface representing standardized variation sequences defined in the Unicode Standard.
 */
export interface StandardizedVariants {
  /**
   * The variation sequence.
   * Example: "[0;31m"
   */
  variation_sequence: string;

  /**
   * The description of the desired appearance.
   * Example: "Red text"
   */
  description: string;

  /**
   * Indicates where the appearance is only different in particular shaping environments.
   * Example: "Terminal, Web"
   */
  shaping_environments: string;
}

export const STANDARDIZED_VARIANTS_FIELDS = [
  "variation_sequence",
  "description",
  "shaping_environments"
];
//#endregion

//#region data-files/v13.0.0/TangutSources.txt
/**
 * This interface represents the data structure for TangutSources.
 */
export interface TangutSources {
    /**
     * The date of the file creation in GMT format.
     * Example: "2020-01-28, 15:31:00 GMT"
     */
    date: string;
    /**
     * The copyright information for the file.
     * Example: "© 2020 Unicode®, Inc."
     */
    copyright: string;
    /**
     * The URL for the terms of use.
     * Example: "http://www.unicode.org/terms_of_use.html"
     */
    terms_of_use_url: string;
    /**
     * The URL for the documentation of the Unicode Character Database.
     * Example: "http://www.unicode.org/reports/tr44/"
     */
    documentation_url: string;
    /**
     * Indicates that this file is a normative contributory data file.
     */
    normative_contributory_data_file: boolean;
}

export const TANGUT_SOURCES_FIELDS = [
    "date",
    "copyright",
    "terms_of_use_url",
    "documentation_url",
    "normative_contributory_data_file"
];
//#endregion

//#region data-files/v13.0.0/USourceData.txt
/**
 * Interface representing the U-source ideographs data.
 */
export interface USourceData {
    /**
     * The U-source ID.
     */
    u_source_id: string;

    /**
     * Text indicating the ideograph's status. Possible values include:
     * - "A": Encoded in Extension A
     * - "B": Encoded in Extension B
     * - "C": Encoded in Extension C
     * - "Comp": Encoded as a compatibility ideograph
     * - "D": Encoded in Extension D
     * - "E": Encoded in Extension E
     * - "F": Encoded in Extension F
     * - "G": Encoded in Extension G
     * - "N": Planned to be submitted for a future extension
     * - "U": Encoded in the URO or as a unified ideograph in the CJK Compatibility Ideographs block
     * - "UK-2015": Submitted by the UK for IRG Working Set 2015
     * - "V": Variant of an encoded character
     * - "W": Not suitable for encoding as a CJK Unified Ideograph
     * - "WS-2017": Submitted by the UTC for IRG Working Set 2017
     * - "X": No action taken
     * - "(UTC-\d{5})|(UCI-\d{5})": Duplicate entries deprecated in favor of other entries; the status value is the identifier of the non-deprecated character
     */
    status: "A" | "B" | "C" | "Comp" | "D" | "E" | "F" | "G" | "N" | "U" | "UK-2015" | "V" | "W" | "WS-2017" | "X" | `"(UTC-\d{5})|(UCI-\d{5})"`;

    /**
     * A Unicode code point. If the status is "V", this specifies the encoded character for which this entry is a variant.
     */
    unicode_code_point: string;

    /**
     * Radical-stroke count.
     */
    radical_stroke_count: number;

    /**
     * Virtual KangXi dictionary position.
     */
    virtual_kangxi_position: number;

    /**
     * Ideographic Description Sequence (IDS), if possible.
     */
    ideographic_description_sequence?: string;

    /**
     * Source(s) of the ideograph.
     */
    sources: string;

    /**
     * General comments regarding the ideograph.
     */
    general_comments?: string;
}

export const USOURCE_DATA_FIELDS = [
    "u_source_id",
    "status",
    "unicode_code_point",
    "radical_stroke_count",
    "virtual_kangxi_position",
    "ideographic_description_sequence",
    "sources",
    "general_comments"
];
//#endregion

//#region data-files/v13.0.0/VerticalOrientation.txt
/**
 * VerticalOrientation interface defines the Vertical_Orientation property values for Unicode characters.
 * 
 * The Vertical_Orientation property can have the following values:
 * - "U": Upright, the same orientation as in the code charts.
 * - "R": Rotated 90 degrees clockwise compared to the code charts.
 * - "Tu": Transformed typographically, with fallback to Upright.
 * - "Tr": Transformed typographically, with fallback to Rotated.
 * 
 * Certain ranges of unassigned code points default to "U". All other code points, assigned and unassigned, that are not listed explicitly are given the value "R".
 */
export interface VerticalOrientation {
    /**
     * Unicode code point value or range of code point values in hexadecimal form.
     */
    code_point: string;
    /**
     * Vertical_Orientation property value, one of the following:
     * - "U"
     * - "R"
     * - "Tu"
     * - "Tr"
     */
    vertical_orientation: "U" | "R" | "Tu" | "Tr";
}

export const VERTICAL_ORIENTATION_FIELDS = [
    "code_point",
    "vertical_orientation"
];
//#endregion

//#region data-files/v13.0.0/extracted/DerivedBidiClass.txt
/**
 * Interface representing the Unicode Character Database derived from the file DerivedBidiClass.
 */
export interface DerivedBidiClass {
    /**
     * The date when the data was generated in ISO 8601 format.
     * Example: "2019-10-21T14:30:28Z"
     */
    date: string;

    /**
     * The copyright information for the Unicode data.
     * Example: "© 2019 Unicode®, Inc."
     */
    copyright: string;

    /**
     * The URL for the terms of use for the Unicode data.
     * Example: "http://www.unicode.org/terms_of_use.html"
     */
    terms_of_use_url: string;

    /**
     * The URL for the documentation of the Unicode Character Database.
     * Example: "http://www.unicode.org/reports/tr44/"
     */
    documentation_url: string;
}

export const DERIVED_BIDI_CLASS_FIELDS = [
    "date",
    "copyright",
    "terms_of_use_url",
    "documentation_url"
];
//#endregion

//#region data-files/v13.0.0/extracted/DerivedBinaryProperties.txt
/**
 * Interface representing the derived binary properties from the Unicode Character Database.
 */
export interface DerivedBinaryProperties {
    /**
     * The date when the data was last updated.
     * Format: YYYY-MM-DD, HH:MM:SS GMT
     * Example: "2019-09-08, 23:31:04 GMT"
     */
    date: string;
    /**
     * The copyright information for the data.
     * Example: "© 2019 Unicode®, Inc."
     */
    copyright: string;
    /**
     * The URL for the terms of use.
     * Format: URL
     * Example: "http://www.unicode.org/terms_of_use.html"
     */
    terms_of_use_url: string;
    /**
     * The URL for the documentation of the Unicode Character Database.
     * Format: URL
     * Example: "http://www.unicode.org/reports/tr44/"
     */
    documentation_url: string;
}

export const DERIVED_BINARY_PROPERTIES_FIELDS = [
    "date",
    "copyright",
    "terms_of_use_url",
    "documentation_url"
];
//#endregion

//#region data-files/v13.0.0/extracted/DerivedCombiningClass.txt
/**
 * Interface representing the DerivedCombiningClass.
 */
export interface DerivedCombiningClass {
    /**
     * The date of the document in ISO 8601 format.
     * Example: "2019-11-13T21:51:57Z"
     */
    date: string;
    /**
     * The copyright information for the document.
     * Example: "© 2019 Unicode®, Inc."
     */
    copyright: string;
    /**
     * The URL for the terms of use.
     * Example: "http://www.unicode.org/terms_of_use.html"
     */
    terms_of_use_url: string;
    /**
     * The URL for the documentation.
     * Example: "http://www.unicode.org/reports/tr44/"
     */
    documentation_url: string;
}

export const DERIVED_COMBINING_CLASS_FIELDS = [
    "date",
    "copyright",
    "terms_of_use_url",
    "documentation_url"
];
//#endregion

//#region data-files/v13.0.0/extracted/DerivedDecompositionType.txt
/**
 * Interface representing the DerivedDecompositionType.
 */
export interface DerivedDecompositionType {
    /**
     * The Unicode character for which the decomposition is defined.
     * Example: "A"
     */
    character: string;

    /**
     * The decomposition mapping for the character.
     * This can be a string or an array of strings representing the decomposed characters.
     * Example: "A" -> "A" or "A" -> ["A", "B"]
     */
    decomposition: string | string[];

    /**
     * The type of decomposition.
     * This can be one of the following: "canonical", "compatibility"
     * Example: "canonical"
     */
    type: "canonical" | "compatibility";
}

export const DERIVED_DECOMPOSITION_TYPE_FIELDS = [
    "character",
    "decomposition",
    "type"
];
//#endregion

//#region data-files/v13.0.0/extracted/DerivedEastAsianWidth.txt
/**
 * Interface representing the Derived East Asian Width data.
 */
export interface DerivedEastAsianWidth {
    /**
     * The Unicode character code point in hexadecimal format.
     * Example: "U+0041" for the character 'A'.
     */
    code_point: string;

    /**
     * The East Asian Width property of the character.
     * Possible values: "N", "A", "H", "W", "F", "Na".
     */
    east_asian_width: "N" | "A" | "H" | "W" | "F" | "Na";

    /**
     * The character itself represented as a string.
     * Example: "A" for the character 'A'.
     */
    character: string;

    /**
     * The name of the character as per Unicode standards.
     * Example: "LATIN CAPITAL LETTER A" for the character 'A'.
     */
    character_name: string;
}

export const DERIVED_EAST_ASIAN_WIDTH_FIELDS = [
    "code_point",
    "east_asian_width",
    "character",
    "character_name"
];
//#endregion

//#region data-files/v13.0.0/extracted/DerivedGeneralCategory.txt
/**
 * Interface representing the Unicode Character Database derived general category.
 */
export interface DerivedGeneralCategory {
    /**
     * The Unicode character category, represented as a string.
     * Example: "Lu" for uppercase letters.
     */
    category: string;

    /**
     * The date when the data was last updated, in ISO 8601 format.
     * Example: "2019-10-21T14:30:32Z"
     */
    date: string;

    /**
     * The copyright information for the Unicode data.
     * Example: "© 2019 Unicode®, Inc."
     */
    copyright: string;

    /**
     * The URL for the terms of use for the Unicode data.
     * Example: "http://www.unicode.org/terms_of_use.html"
     */
    terms_of_use_url: string;

    /**
     * The documentation URL for the Unicode Character Database.
     * Example: "http://www.unicode.org/reports/tr44/"
     */
    documentation_url: string;
}

export const DERIVED_GENERAL_CATEGORY_FIELDS = [
    "category",
    "date",
    "copyright",
    "terms_of_use_url",
    "documentation_url"
];
//#endregion

//#region data-files/v13.0.0/extracted/DerivedJoiningGroup.txt
/**
 * Interface representing the Unicode Character Database derived joining group.
 */
export interface DerivedJoiningGroup {
    /**
     * The name of the derived joining group.
     * Example: "Left"
     */
    name: string;
    
    /**
     * The code point range for the derived joining group.
     * Format: "U+XXXX..U+YYYY"
     * Example: "U+0000..U+007F"
     */
    code_point_range: string;
    
    /**
     * The properties associated with the derived joining group.
     * Example: "L", "R"
     */
    properties: string[];
}

export const DERIVED_JOINING_GROUP_FIELDS = [
    "name",
    "code_point_range",
    "properties"
];
//#endregion

//#region data-files/v13.0.0/extracted/DerivedJoiningType.txt
/**
 * Interface representing the DerivedJoiningType.
 */
export interface DerivedJoiningType {
    /**
     * The character that represents the derived joining type.
     * Example: 'U' for Unicode.
     */
    derived_joining_type: string;

    /**
     * The description of the derived joining type.
     * Example: 'Left' for left joining.
     */
    description: string;

    /**
     * The code point of the character.
     * Example: 'U+0061' for the character 'a'.
     */
    code_point: string;

    /**
     * The category of the character.
     * Example: 'Ll' for lowercase letter.
     */
    category: string;
}

export const DERIVED_JOINING_TYPE_FIELDS = [
    "derived_joining_type",
    "description",
    "code_point",
    "category"
];
//#endregion

//#region data-files/v13.0.0/extracted/DerivedLineBreak.txt
/**
 * Interface representing the Unicode Character Database derived line break properties.
 */
export interface DerivedLineBreak {
    /**
     * The date when the data was last updated.
     * Format: "YYYY-MM-DD HH:MM:SS GMT"
     * Example: "2020-02-17 18:43:18 GMT"
     */
    date: string;

    /**
     * The copyright information for the Unicode data.
     * Example: "© 2020 Unicode®, Inc."
     */
    copyright: string;

    /**
     * The URL for the terms of use for the Unicode data.
     * Example: "http://www.unicode.org/terms_of_use.html"
     */
    terms_of_use_url: string;

    /**
     * The URL for the documentation of the Unicode Character Database.
     * Example: "http://www.unicode.org/reports/tr44/"
     */
    documentation_url: string;
}

export const DERIVED_LINE_BREAK_FIELDS = [
    "date",
    "copyright",
    "terms_of_use_url",
    "documentation_url"
];
//#endregion

//#region data-files/v13.0.0/extracted/DerivedName.txt
/**
 * This interface represents the derived names of Unicode characters based on their code points.
 */
export interface DerivedName {
  /**
   * Unicode code point value or range of code point values.
   * Example: U+4E12 or U+2F89F
   */
  code_point: string;

  /**
   * Name property value or pattern derived from the code point.
   * Patterns may contain a '*' character which is replaced by the code point in hex.
   * Example: CJK UNIFIED IDEOGRAPH-* becomes CJK UNIFIED IDEOGRAPH-4E12 for U+4E12.
   */
  name_property: string;
}

export const DERIVED_NAME_FIELDS = [
  "code_point",
  "name_property"
];
//#endregion

//#region data-files/v13.0.0/extracted/DerivedNumericType.txt
/**
 * Interface representing the DerivedNumericType data structure.
 */
export interface DerivedNumericType {
    /**
     * The version of the Unicode data.
     * Format: "X.Y.Z" where X, Y, and Z are integers.
     * Example: "13.0.0"
     */
    version: string;

    /**
     * The date when the data was last updated.
     * Format: ISO 8601 date string.
     * Example: "2019-09-08T23:31:09Z"
     */
    date: string;

    /**
     * The copyright information for the Unicode data.
     * Example: "© 2019 Unicode®, Inc."
     */
    copyright: string;

    /**
     * The URL for the terms of use.
     * Format: Valid URL string.
     * Example: "http://www.unicode.org/terms_of_use.html"
     */
    terms_of_use: string;

    /**
     * The documentation URL for the Unicode Character Database.
     * Format: Valid URL string.
     * Example: "http://www.unicode.org/reports/tr44/"
     */
    documentation_url: string;
}

export const DERIVED_NUMERIC_TYPE_FIELDS = [
    "version",
    "date",
    "copyright",
    "terms_of_use",
    "documentation_url"
];
//#endregion

//#region data-files/v13.0.0/extracted/DerivedNumericValues.txt
/**
 * Interface representing the derived numeric values as per Unicode Character Database.
 */
export interface DerivedNumericValues {
    /**
     * The version of the derived numeric values.
     * Format: "X.Y.Z" where X, Y, and Z are integers.
     * Example: "13.0.0"
     */
    version: "string";

    /**
     * The date when the derived numeric values were generated.
     * Format: RFC 3339 date-time string.
     * Example: "2019-09-08T23:31:10Z"
     */
    date: "string";

    /**
     * The copyright information for the derived numeric values.
     * Example: "© 2019 Unicode®, Inc."
     */
    copyright: "string";

    /**
     * The URL for the terms of use.
     * Format: URL string.
     * Example: "http://www.unicode.org/terms_of_use.html"
     */
    terms_of_use: "string";

    /**
     * The URL for the documentation of the Unicode Character Database.
     * Format: URL string.
     * Example: "http://www.unicode.org/reports/tr44/"
     */
    documentation_url: "string";
}

export const DERIVED_NUMERIC_VALUES_FIELDS = [
    "version",
    "date",
    "copyright",
    "terms_of_use",
    "documentation_url"
];
//#endregion

//#region data-files/v13.0.0/emoji/emoji-data.txt
/**
 * Emoji Data for UTS #51
 * Version: 13.0
 */
export interface emoji_data {
    /**
     * The code point(s) of the emoji, represented in hexadecimal format.
     * Example: "1F600"
     */
    codepoint: string;

    /**
     * The property of the emoji, indicating its category or type.
     * Example: "face"
     */
    property: string;

    /**
     * Comments or additional information about the emoji.
     * Example: "grinning face"
     */
    comments: string;
}

export const EMOJI_DATA_FIELDS = [
    "codepoint",
    "property",
    "comments"
];
//#endregion

//#region data-files/v13.0.0/emoji/emoji-variation-sequences.txt
/**
 * Emoji Variation Sequences for UTS #51
 * Version: 13.0
 */
export interface emoji_variation_sequences {
    /**
     * The date when the document was created.
     * Format: YYYY-MM-DD
     * Example: "2020-01-21"
     */
    date: string;
    /**
     * The time when the document was created.
     * Format: HH:MM:SS GMT
     * Example: "07:15:05 GMT"
     */
    time: string;
    /**
     * Copyright information regarding the document.
     * Example: "© 2020 Unicode®, Inc."
     */
    copyright: string;
    /**
     * The version of the Unicode standard referenced.
     * Example: "13.0"
     */
    version: string;
    /**
     * Documentation URL for usage and further information.
     * Example: "http://www.unicode.org/reports/tr51"
     */
    documentation_url: string;
}

export const EMOJI_VARIATION_SEQUENCES_FIELDS = [
    "date",
    "time",
    "copyright",
    "version",
    "documentation_url"
];
//#endregion

//#region data-files/v13.0.0/auxiliary/GraphemeBreakProperty.txt
/**
 * Interface representing the Grapheme Break Property data.
 */
export interface GraphemeBreakProperty {
    /**
     * The character or character sequence.
     * Example: "a"
     */
    character: string;
    
    /**
     * The grapheme break property value for the character.
     * Example: "CR"
     */
    property: "CR" | "LF" | "Control" | "Extend" | "SpacingMark" | "L" | "V" | "T" | "LV" | "LVT";
}

export const GRAPHEME_BREAK_PROPERTY_FIELDS = [
    "character",
    "property"
];
//#endregion

//#region data-files/v13.0.0/auxiliary/GraphemeBreakTest.txt
/**
 * GraphemeBreakTest interface representing the default grapheme cluster break test data.
 */
export interface GraphemeBreakTest {
    /**
     * A string containing hex Unicode code points.
     * Example: "0041 0042 0043"
     */
    code_points: string;
    /**
     * An optional comment associated with the code points.
     * Example: "# This is a comment"
     */
    comment?: string;
}

export const GRAPHEME_BREAK_TEST_FIELDS = [
    "code_points",
    "comment"
];
//#endregion

//#region data-files/v13.0.0/auxiliary/LineBreakTest.txt
/**
 * Interface representing the default line break test as per Unicode Character Database.
 */
export interface LineBreakTest {
    /**
     * A string containing hex Unicode code points.
     * Format: <string> (# <comment>)?
     * Example: "0041 0042 0043 (# Comment)"
     */
    line_break: string;
}

export const LINE_BREAK_TEST_FIELDS = [
    "line_break"
];
//#endregion

//#region data-files/v13.0.0/auxiliary/SentenceBreakProperty.txt
/**
 * Interface representing the properties defined in the SentenceBreakProperty Unicode Character Database.
 */
export interface SentenceBreakProperty {
    /**
     * The Unicode character code point.
     * Example: "U+0041" for the character 'A'.
     */
    code_point: string;

    /**
     * The category of the character according to Unicode.
     * Example: "Uppercase Letter", "Lowercase Letter", etc.
     */
    category: string;

    /**
     * The specific property value for the character.
     * Example: "AL" for an alphabetic character.
     */
    property_value: string;

    /**
     * Additional notes or comments regarding the character.
     * Example: "This character is used in various languages."
     */
    notes: string;
}

export const SENTENCE_BREAK_PROPERTY_FIELDS = [
    "code_point",
    "category",
    "property_value",
    "notes"
];
//#endregion

//#region data-files/v13.0.0/auxiliary/SentenceBreakTest.txt
/**
 * Interface representing the default sentence break test data.
 */
export interface SentenceBreakTest {
    /**
     * A string containing hex Unicode code points.
     * Example: "0041 0042 0043"
     */
    code_points: string;
    /**
     * An optional comment associated with the code points.
     * Example: "# This is a comment"
     */
    comment?: string;
}

export const SENTENCE_BREAK_TEST_FIELDS = [
    "code_points",
    "comment"
];
//#endregion

//#region data-files/v13.0.0/auxiliary/WordBreakProperty.txt
/**
 * Interface representing the properties related to word breaking as defined in the Unicode Character Database.
 */
export interface WordBreakProperty {
    /**
     * The character category for word breaking.
     * Example: "AL" for alphabetic characters.
     */
    character_category: "AL" | "CR" | "EX" | "FO" | "HY" | "ID" | "IN" | "IS" | "JL" | "JT" | "LF" | "ML" | "NL" | "NS" | "NU" | "OP" | "PO" | "QU" | "SA" | "SG" | "SP" | "SY" | "XX";

    /**
     * The word break property value.
     * Example: "W" for a word break opportunity.
     */
    word_break_property: "W" | "N" | "B" | "S" | "X";

    /**
     * The Unicode code point of the character.
     * Example: 0x0041 for 'A'.
     */
    code_point: number;
}

export const WORD_BREAK_PROPERTY_FIELDS = [
    "character_category",
    "word_break_property",
    "code_point"
];
//#endregion

//#region data-files/v13.0.0/auxiliary/WordBreakTest.txt
/**
 * Interface representing the WordBreakTest data structure.
 */
export interface WordBreakTest {
    /**
     * A string containing hex Unicode code points, with optional comments.
     * Example: "0041 (# comment)"
     */
    string: string;
}

export const WORD_BREAK_TEST_FIELDS = [
    "string"
];
//#endregion

