// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1


// #region ArabicShaping
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface ArabicShaping {
  code_point: string
  name: string
  joining_type: "R" | "L" | "D" | "C" | "U" | "T"
  joining_group: string
}

export const ARABIC_SHAPING_FIELDS = [
  "code_point",
  "name",
  "joining_type",
  "joining_group"
];

// #endregion

// #region BidiMirroring
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface BidiMirroring {
  code_point: string
  mirrored_code_point: string
}

export const BIDI_MIRRORING_FIELDS = [
  "code_point",
  "mirrored_code_point"
];

// #endregion

// #region Blocks
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface Blocks {
  start_code: string
  end_code: string
  block_name: string
}

export const BLOCKS_FIELDS = [
  "start_code",
  "end_code",
  "block_name"
];

// #endregion

// #region CaseFolding
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface CaseFolding {
  code: string
  status: "C" | "F" | "S" | "T"
  mapping: string
  name: string
}

export const CASE_FOLDING_FIELDS = [
  "code",
  "status",
  "mapping",
  "name"
];

// #endregion

// #region CompositionExclusions
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface CompositionExclusions {
  code_point: string
  name: string
}

export const COMPOSITION_EXCLUSIONS_FIELDS = [
  "code_point",
  "name"
];

// #endregion

// #region DerivedAge
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface DerivedAge {
  code_point: string
  name: string
  age: string
}

export const DERIVED_AGE_FIELDS = [
  "code_point",
  "name",
  "age"
];

// #endregion

// #region DerivedCoreProperties
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface DerivedCoreProperties {
  code_point: string
  name: string
}

export const DERIVED_CORE_PROPERTIES_FIELDS = [
  "code_point",
  "name"
];

// #endregion

// #region DerivedNormalizationProps
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface DerivedNormalizationProps {
  code_point: string
  name: string
}

export const DERIVED_NORMALIZATION_PROPS_FIELDS = [
  "code_point",
  "name"
];

// #endregion

// #region EastAsianWidth
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface EastAsianWidth {
  unicode_value: string
  east_asian_width_property: "N" | "A" | "H" | "W" | "F" | "Na"
}

export const EAST_ASIAN_WIDTH_FIELDS = [
  "unicode_value",
  "east_asian_width_property"
];

// #endregion

// #region HangulSyllableType
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface HangulSyllableType {
  code_point: string
  name: string
}

export const HANGUL_SYLLABLE_TYPE_FIELDS = [
  "code_point",
  "name"
];

// #endregion

// #region Jamo
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface Jamo {
  code_point: string
  jamo_short_name: string
}

export const JAMO_FIELDS = [
  "code_point",
  "jamo_short_name"
];

// #endregion

// #region LineBreak
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface LineBreak {
  unicode_value: string
  line_break_property: "BK" | "CR" | "LF" | "CM" | "SG" | "GL" | "CB" | "SP" | "ZW" | "NL" | "WJ" | "JL" | "JV" | "JT" | "H2" | "H3" | "XX" | "OP" | "CL" | "QU" | "NS" | "EX" | "SY" | "IS" | "PR" | "PO" | "NU" | "AL" | "ID" | "IN" | "HY" | "BB" | "BA" | "SA" | "AI" | "B2"
}

export const LINE_BREAK_FIELDS = [
  "unicode_value",
  "line_break_property"
];

// #endregion

// #region NamedSequences
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface NamedSequences {
  name_of_sequence: string
  code_point_sequence: string
}

export const NAMED_SEQUENCES_FIELDS = [
  "name_of_sequence",
  "code_point_sequence"
];

// #endregion

// #region NormalizationCorrections
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface NormalizationCorrections {
  unicode_code_point: string
  original_decomposition: string
  corrected_decomposition: string
  unicode_version: string
  comment: string
}

export const NORMALIZATION_CORRECTIONS_FIELDS = [
  "unicode_code_point",
  "original_decomposition",
  "corrected_decomposition",
  "unicode_version",
  "comment"
];

// #endregion

// #region PropList
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface PropList {
  code_point: string
  name: string
}

export const PROP_LIST_FIELDS = [
  "code_point",
  "name"
];

// #endregion

// #region PropertyAliases
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface PropertyAliases {
  abbreviated_name: string
  long_name: string
  additional_aliases: string[]
  property_value: string
  property_name: string
}

export const PROPERTY_ALIASES_FIELDS = [
  "abbreviated_name",
  "long_name",
  "additional_aliases",
  "property_value",
  "property_name"
];

// #endregion

// #region PropertyValueAliases
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface PropertyValueAliases {
  property: string
  abbreviated_name: string
  long_name: string
  additional_aliases: string[]
}

export const PROPERTY_VALUE_ALIASES_FIELDS = [
  "property",
  "abbreviated_name",
  "long_name",
  "additional_aliases"
];

// #endregion

// #region Scripts
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface Scripts {
  code_point: string
  name: string
}

export const SCRIPTS_FIELDS = [
  "code_point",
  "name"
];

// #endregion

// #region SpecialCasing
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface SpecialCasing {
  code: string
  lower: string
  title: string
  upper: string
  condition_list: string[]
  comment: string
}

export const SPECIAL_CASING_FIELDS = [
  "code",
  "lower",
  "title",
  "upper",
  "condition_list",
  "comment"
];

// #endregion

// #region StandardizedVariants
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface StandardizedVariants {
  variation_sequence: string
  description: string
  shaping_environment: string
}

export const STANDARDIZED_VARIANTS_FIELDS = [
  "variation_sequence",
  "description",
  "shaping_environment"
];

// #endregion

// #region Unihan
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface Unihan {
  code_point: string
  name: string
  joining_type: "R" | "L" | "D" | "C" | "U" | "T"
  joining_group: string
}

export const UNIHAN_FIELDS = [
  "code_point",
  "name",
  "joining_type",
  "joining_group"
];

// #endregion

// #region DerivedBidiClass
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface DerivedBidiClass {
  derived_bidi_class: string
  date: string
  unicode_character_database: string
  copyright: string
  terms_of_use: string
  documentation: string
}

export const DERIVED_BIDI_CLASS_FIELDS = [
  "derived_bidi_class",
  "date",
  "unicode_character_database",
  "copyright",
  "terms_of_use",
  "documentation"
];

// #endregion

// #region DerivedBinaryProperties
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface DerivedBinaryProperties {
  code_point: string
  name: string
}

export const DERIVED_BINARY_PROPERTIES_FIELDS = [
  "code_point",
  "name"
];

// #endregion

// #region DerivedCombiningClass
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface DerivedCombiningClass {
  derived_combining_class: string
  date: string
  unicode_character_database: string
  copyright: string
  terms_of_use: string
  documentation: string
}

export const DERIVED_COMBINING_CLASS_FIELDS = [
  "derived_combining_class",
  "date",
  "unicode_character_database",
  "copyright",
  "terms_of_use",
  "documentation"
];

// #endregion

// #region DerivedDecompositionType
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface DerivedDecompositionType {
  derived_decomposition_type: string
  date: string
  unicode_character_database: string
  copyright: string
  terms_of_use: string
  documentation: string
}

export const DERIVED_DECOMPOSITION_TYPE_FIELDS = [
  "derived_decomposition_type",
  "date",
  "unicode_character_database",
  "copyright",
  "terms_of_use",
  "documentation"
];

// #endregion

// #region DerivedEastAsianWidth
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface DerivedEastAsianWidth {
  code_point: string
  name: string
}

export const DERIVED_EAST_ASIAN_WIDTH_FIELDS = [
  "code_point",
  "name"
];

// #endregion

// #region DerivedGeneralCategory
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface DerivedGeneralCategory {
  code_point: string
  name: string
}

export const DERIVED_GENERAL_CATEGORY_FIELDS = [
  "code_point",
  "name"
];

// #endregion

// #region DerivedJoiningGroup
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface DerivedJoiningGroup {
  code_point: string
  name: string
}

export const DERIVED_JOINING_GROUP_FIELDS = [
  "code_point",
  "name"
];

// #endregion

// #region DerivedJoiningType
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface DerivedJoiningType {
  code_point: string
  name: string
  derived_joining_type: string
}

export const DERIVED_JOINING_TYPE_FIELDS = [
  "code_point",
  "name",
  "derived_joining_type"
];

// #endregion

// #region DerivedLineBreak
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface DerivedLineBreak {
  code_point: string
  name: string
}

export const DERIVED_LINE_BREAK_FIELDS = [
  "code_point",
  "name"
];

// #endregion

// #region DerivedNumericType
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface DerivedNumericType {
  code_point: string
  name: string
}

export const DERIVED_NUMERIC_TYPE_FIELDS = [
  "code_point",
  "name"
];

// #endregion

// #region DerivedNumericValues
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface DerivedNumericValues {
  code_point: string
  name: string
}

export const DERIVED_NUMERIC_VALUES_FIELDS = [
  "code_point",
  "name"
];

// #endregion

// #region GraphemeBreakProperty
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface GraphemeBreakProperty {
  code_point: string
  name: string
}

export const GRAPHEME_BREAK_PROPERTY_FIELDS = [
  "code_point",
  "name"
];

// #endregion

// #region SentenceBreakProperty
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface SentenceBreakProperty {
  code_point: string
  name: string
}

export const SENTENCE_BREAK_PROPERTY_FIELDS = [
  "code_point",
  "name"
];

// #endregion

// #region WordBreakProperty
// This file is generated by ucd codegen. Do not edit this file directly.
// Unicode Version: 4.1

export interface WordBreakProperty {
  code_point: string
  name: string
}

export const WORD_BREAK_PROPERTY_FIELDS = [
  "code_point",
  "name"
];

// #endregion
