name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

permissions: {}

jobs:
  ci:
    uses: luxass/shared-workflows/.github/workflows/ci.yaml@56bd9148cc90ee377d1e6fa3a32e43d18859dfe1 # v0.4.2
    permissions:
      contents: read
    with:
      fmt: true
      fmt-script: "fmt:check"
